// <auto-generated />
namespace PNet_Again.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class world1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(world1));
        
        string IMigrationMetadata.Id
        {
            get { return "201903232335287_world-1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
